#ifndef QP_ENUMS_H
#define QP_ENUMS_H

enum QP_BRUSH_TYPE {ADD, SUBTRACT, COMBINE, OVERLAY, OVERWRITE, MASK};
enum QP_COLOR_MODE {SEQUENTIAL, RANDOM};

namespace qpEnums {

    enum QP_PATTERN_EVENT {CYCLE, FINISH, ACTIVATE, DEACTIVATE};
    enum QP_COLOR_MODE {SEQUENTIAL, RANDOM};

};

#endif